// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// AzureIdentity is the specification of the identity data structure.
type AzureIdentity struct {
	pulumi.CustomResourceState

	ApiVersion pulumi.StringPtrOutput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrOutput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrOutput `pulumi:"metadata"`
	// AzureIdentitySpec describes the credential specifications of an identity on Azure.
	Spec AzureIdentitySpecPtrOutput `pulumi:"spec"`
	// AzureIdentityStatus contains the replica status of the resource.
	Status AzureIdentityStatusPtrOutput `pulumi:"status"`
}

// NewAzureIdentity registers a new resource with the given unique name, arguments, and options.
func NewAzureIdentity(ctx *pulumi.Context,
	name string, args *AzureIdentityArgs, opts ...pulumi.ResourceOption) (*AzureIdentity, error) {
	if args == nil {
		args = &AzureIdentityArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("aadpodidentity.k8s.io/v1")
	args.Kind = pulumi.StringPtr("AzureIdentity")
	var resource AzureIdentity
	err := ctx.RegisterResource("kubernetes:aadpodidentity.k8s.io/v1:AzureIdentity", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureIdentity gets an existing AzureIdentity resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureIdentity(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureIdentityState, opts ...pulumi.ResourceOption) (*AzureIdentity, error) {
	var resource AzureIdentity
	err := ctx.ReadResource("kubernetes:aadpodidentity.k8s.io/v1:AzureIdentity", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureIdentity resources.
type azureIdentityState struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AzureIdentitySpec describes the credential specifications of an identity on Azure.
	Spec *AzureIdentitySpec `pulumi:"spec"`
	// AzureIdentityStatus contains the replica status of the resource.
	Status *AzureIdentityStatus `pulumi:"status"`
}

type AzureIdentityState struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AzureIdentitySpec describes the credential specifications of an identity on Azure.
	Spec AzureIdentitySpecPtrInput
	// AzureIdentityStatus contains the replica status of the resource.
	Status AzureIdentityStatusPtrInput
}

func (AzureIdentityState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureIdentityState)(nil)).Elem()
}

type azureIdentityArgs struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AzureIdentitySpec describes the credential specifications of an identity on Azure.
	Spec *AzureIdentitySpec `pulumi:"spec"`
	// AzureIdentityStatus contains the replica status of the resource.
	Status *AzureIdentityStatus `pulumi:"status"`
}

// The set of arguments for constructing a AzureIdentity resource.
type AzureIdentityArgs struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AzureIdentitySpec describes the credential specifications of an identity on Azure.
	Spec AzureIdentitySpecPtrInput
	// AzureIdentityStatus contains the replica status of the resource.
	Status AzureIdentityStatusPtrInput
}

func (AzureIdentityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureIdentityArgs)(nil)).Elem()
}

type AzureIdentityInput interface {
	pulumi.Input

	ToAzureIdentityOutput() AzureIdentityOutput
	ToAzureIdentityOutputWithContext(ctx context.Context) AzureIdentityOutput
}

func (*AzureIdentity) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureIdentity)(nil))
}

func (i *AzureIdentity) ToAzureIdentityOutput() AzureIdentityOutput {
	return i.ToAzureIdentityOutputWithContext(context.Background())
}

func (i *AzureIdentity) ToAzureIdentityOutputWithContext(ctx context.Context) AzureIdentityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureIdentityOutput)
}

type AzureIdentityOutput struct {
	*pulumi.OutputState
}

func (AzureIdentityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureIdentity)(nil))
}

func (o AzureIdentityOutput) ToAzureIdentityOutput() AzureIdentityOutput {
	return o
}

func (o AzureIdentityOutput) ToAzureIdentityOutputWithContext(ctx context.Context) AzureIdentityOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(AzureIdentityOutput{})
}
