// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// AzureAssignedIdentity contains the identity <-> pod mapping which is matched.
type AzureAssignedIdentity struct {
	pulumi.CustomResourceState

	ApiVersion pulumi.StringPtrOutput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrOutput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrOutput `pulumi:"metadata"`
	// AzureAssignedIdentitySpec contains the relationship between an AzureIdentity and an AzureIdentityBinding.
	Spec AzureAssignedIdentitySpecPtrOutput `pulumi:"spec"`
	// AzureAssignedIdentityStatus contains the replica status of the resource.
	Status AzureAssignedIdentityStatusPtrOutput `pulumi:"status"`
}

// NewAzureAssignedIdentity registers a new resource with the given unique name, arguments, and options.
func NewAzureAssignedIdentity(ctx *pulumi.Context,
	name string, args *AzureAssignedIdentityArgs, opts ...pulumi.ResourceOption) (*AzureAssignedIdentity, error) {
	if args == nil {
		args = &AzureAssignedIdentityArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("aadpodidentity.k8s.io/v1")
	args.Kind = pulumi.StringPtr("AzureAssignedIdentity")
	var resource AzureAssignedIdentity
	err := ctx.RegisterResource("kubernetes:aadpodidentity.k8s.io/v1:AzureAssignedIdentity", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAzureAssignedIdentity gets an existing AzureAssignedIdentity resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAzureAssignedIdentity(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AzureAssignedIdentityState, opts ...pulumi.ResourceOption) (*AzureAssignedIdentity, error) {
	var resource AzureAssignedIdentity
	err := ctx.ReadResource("kubernetes:aadpodidentity.k8s.io/v1:AzureAssignedIdentity", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AzureAssignedIdentity resources.
type azureAssignedIdentityState struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AzureAssignedIdentitySpec contains the relationship between an AzureIdentity and an AzureIdentityBinding.
	Spec *AzureAssignedIdentitySpec `pulumi:"spec"`
	// AzureAssignedIdentityStatus contains the replica status of the resource.
	Status *AzureAssignedIdentityStatus `pulumi:"status"`
}

type AzureAssignedIdentityState struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AzureAssignedIdentitySpec contains the relationship between an AzureIdentity and an AzureIdentityBinding.
	Spec AzureAssignedIdentitySpecPtrInput
	// AzureAssignedIdentityStatus contains the replica status of the resource.
	Status AzureAssignedIdentityStatusPtrInput
}

func (AzureAssignedIdentityState) ElementType() reflect.Type {
	return reflect.TypeOf((*azureAssignedIdentityState)(nil)).Elem()
}

type azureAssignedIdentityArgs struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// AzureAssignedIdentitySpec contains the relationship between an AzureIdentity and an AzureIdentityBinding.
	Spec *AzureAssignedIdentitySpec `pulumi:"spec"`
	// AzureAssignedIdentityStatus contains the replica status of the resource.
	Status *AzureAssignedIdentityStatus `pulumi:"status"`
}

// The set of arguments for constructing a AzureAssignedIdentity resource.
type AzureAssignedIdentityArgs struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	// AzureAssignedIdentitySpec contains the relationship between an AzureIdentity and an AzureIdentityBinding.
	Spec AzureAssignedIdentitySpecPtrInput
	// AzureAssignedIdentityStatus contains the replica status of the resource.
	Status AzureAssignedIdentityStatusPtrInput
}

func (AzureAssignedIdentityArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*azureAssignedIdentityArgs)(nil)).Elem()
}

type AzureAssignedIdentityInput interface {
	pulumi.Input

	ToAzureAssignedIdentityOutput() AzureAssignedIdentityOutput
	ToAzureAssignedIdentityOutputWithContext(ctx context.Context) AzureAssignedIdentityOutput
}

func (*AzureAssignedIdentity) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureAssignedIdentity)(nil))
}

func (i *AzureAssignedIdentity) ToAzureAssignedIdentityOutput() AzureAssignedIdentityOutput {
	return i.ToAzureAssignedIdentityOutputWithContext(context.Background())
}

func (i *AzureAssignedIdentity) ToAzureAssignedIdentityOutputWithContext(ctx context.Context) AzureAssignedIdentityOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureAssignedIdentityOutput)
}

type AzureAssignedIdentityOutput struct {
	*pulumi.OutputState
}

func (AzureAssignedIdentityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureAssignedIdentity)(nil))
}

func (o AzureAssignedIdentityOutput) ToAzureAssignedIdentityOutput() AzureAssignedIdentityOutput {
	return o
}

func (o AzureAssignedIdentityOutput) ToAzureAssignedIdentityOutputWithContext(ctx context.Context) AzureAssignedIdentityOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(AzureAssignedIdentityOutput{})
}
